apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pipelines.fullname" . }}-node-templates-upgrade-{{ randAlpha 8 | lower }}
  labels:
    app.kubernetes.io/name: {{ include "pipelines.name" . }}
    helm.sh/chart: {{ include "pipelines.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    component: {{ include "pipelines.chart" . }}-node
  annotations:
    "helm.sh/hook-weight": "1"
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    #"helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pipelines.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: {{ include "pipelines.chart" . }}-node
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "pipelines.fullname" . }}-api-setup
      containers:
      - name: node-templates-upgrade
        image: "{{ .Values.imageRegistry }}/{{ .Values.pipelinesInit.image.repository }}:{{ default .Chart.AppVersion .Values.pipelinesInit.image.tag }}"
        imagePullPolicy: {{ .Values.pipelinesInit.image.pullPolicy }}
        env:
        - name: PIPELINES_API_IP
          value: {{ include "pipelines.api.name" . }}
        - name: PIPELINES_API_PORT
          value: {{ .Values.api.service.port | quote }}
        - name: API_TOKEN
          valueFrom:
            secretKeyRef: 
              name: {{ default (include "pipelines.fullname" .) .Values.existingSecret }}
              key: api-token
        - name: TMP_DIR
          value: /tmp
        command:
        - '/bin/sh'
        - '-c'
        - >
          echo Prepare scripts;
          cp -f /init-scripts/wait-for-api.sh /scripts;
          chmod +x /scripts/wait-for-api.sh;
          cp -f /init-scripts/createDefaultNodesConfigs.sh /scripts;
          chmod +x /scripts/createDefaultNodesConfigs.sh;
          /scripts/wait-for-api.sh;
          echo Initialize Nodes Configs;
          /scripts/createDefaultNodesConfigs.sh;
        volumeMounts:
        - name: api-setup
          mountPath: "/init-scripts"
        - name: nodes-setup
          mountPath: "/node-templates"
      volumes:
      - name: api-setup
        configMap:
          name: {{ include "pipelines.fullname" . }}-api-setup-scripts
      - name: nodes-setup
        configMap:
          name: {{ include "pipelines.fullname" . }}-node-templates
