{{- if not .Values.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pipelines.fullname" . }}-api-secrets
  labels:
    app.kubernetes.io/name: {{ include "pipelines.name" . }}
    helm.sh/chart: {{ include "pipelines.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    component: {{ include "pipelines.api.name" . }}
type: Opaque
data:
{{- if .Values.postgresql.enabled }}
  db-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
{{- else }}
  db-password: {{ .Values.global.postgresql.password | b64enc | quote }}
{{- end }}
  rt-password: {{ .Values.api.artifactory.password | b64enc | quote }}
  api-token: {{ .Values.api.token | b64enc | quote }}
#
{{- if .Values.api.rabbitMq.url }}
  msg-external-url: {{ (printf "amqp://%s:%s@%s/shippable" .Values.api.rabbitMq.user .Values.api.rabbitMq.userPassword .Values.api.rabbitMq.url) | b64enc }}
  msg-external-root-url: {{ (printf "amqp://%s:%s@%s/shippableRoot" .Values.api.rabbitMq.uiUser .Values.api.rabbitMq.uiUserPassword .Values.api.rabbitMq.url) | b64enc }}
{{- else }}
  {{- if .Values.rabbitmq.enabled }}
  msg-external-url: {{ (printf "amqp://%s:%s@%s-rabbitmq:%v/shippable" .Values.api.rabbitMq.user .Values.api.rabbitMq.userPassword .Release.Name .Values.rabbitmq.service.port) | b64enc }}
  msg-external-root-url: {{ (printf "amqp://%s:%s@%s-rabbitmq:%v/shippableRoot" .Values.api.rabbitMq.user .Values.api.rabbitMq.userPassword .Release.Name .Values.rabbitmq.service.port) | b64enc }}
  {{- else }}
  msg-external-url: {{ (printf "amqp://%s:%s@%s:%v/shippable" .Values.api.rabbitMq.user .Values.api.rabbitMq.userPassword (include "pipelines.msg.name" .) (.Values.msg.rabbitmqNodePort )) | b64enc }}
  msg-external-root-url: {{ (printf "amqp://%s:%s@%s:%v/shippableRoot" .Values.api.rabbitMq.user .Values.api.rabbitMq.userPassword (include "pipelines.msg.name" .) (.Values.msg.rabbitmqNodePort)) | b64enc }}
  {{- end }} 
{{- end }}
#
  rabbitmq-admin-password: {{ .Values.api.rabbitMq.userPassword | b64enc | quote }}
  rabbitmq-adminui-password: {{ .Values.api.rabbitMq.uiUserPassword | b64enc | quote }}
{{- end }}
