{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "pipelines.fullname" . }}-api-setup
  labels:
    app.kubernetes.io/name: {{ include "pipelines.name" . }}
    helm.sh/chart: {{ include "pipelines.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    component: pipelines-api-setup
rules:
- apiGroups:
  - "*"
  resources:
  - secrets
  - configmaps
  - serviceaccounts
  verbs:
  - get
  - list
  - create
  - update
  - patch
{{- end }}
