apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipelines.pipesync.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "pipelines.name" . }}
    helm.sh/chart: {{ include "pipelines.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    component: {{ include "pipelines.pipesync.name" . }}
spec:
  replicas: {{ .Values.pipelineSync.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pipelines.pipesync.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pipelines.pipesync.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/components-configmap.yaml") . | sha256sum }}
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
    {{- end }}
      initContainers:
        - name: wait-for-api
          image: "{{ .Values.initContainerImage }}"
          imagePullPolicy: {{ .Values.pipelineSync.image.pullPolicy }}
          command:
          - 'sh'
          - '-c'
          - >
            echo "Waiting for Pipelines API to come up...";
            until nc -z -w 2 {{ include "pipelines.api.name" . }} {{ .Values.api.service.port }} && echo API ok; do
              sleep 2;
            done;
      containers:
        - name: api
          image: "{{ .Values.pipelineSync.image.repository }}:{{ default .Chart.AppVersion .Values.pipelineSync.image.tag }}"
          imagePullPolicy: {{ .Values.pipelineSync.image.pullPolicy }}
          env:
            - name: COMPONENT
              value: pipelineSync
            - name: SHIPPABLE_API_TOKEN
              valueFrom:
                secretKeyRef: 
                  name: {{ include "pipelines.fullname" . }}-api-secrets
                  key: api-token
          envFrom:
            - configMapRef:
                name: {{ include "pipelines.fullname" . }}-components-config
          workingDir: /shippable/micro/nod/pipelineSync
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.pipelineSync.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.pipelineSync.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.pipelineSync.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
