apiVersion: v1
kind: Service
metadata:
  name: {{ include "pipelines.vault.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "pipelines.name" . }}
    helm.sh/chart: {{ include "pipelines.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    component: {{ include "pipelines.vault.name" . }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.vault.service.port }}
      # nodePort: 30100
      targetPort: 30100
      protocol: TCP
    - name: server
      port: 30101
      protocol: TCP  
  selector:
      app.kubernetes.io/name: {{ include "pipelines.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: {{ include "pipelines.vault.name" . }}
