apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipelines.www.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "pipelines.name" . }}
    helm.sh/chart: {{ include "pipelines.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    component: {{ include "pipelines.www.name" . }}
spec:
  replicas: {{ .Values.www.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pipelines.www.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: {{ include "pipelines.www.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pipelines.www.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: {{ include "pipelines.www.name" . }}
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/www-configmap.yaml") . | sha256sum }}
        checksum/config: {{ include (print .Template.BasePath "/api-configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "pipelines.fullname" . }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
    {{- end }}
      initContainers:
        - name: wait-for-api
          image: "{{ .Values.initContainerImage }}"
          imagePullPolicy: {{ .Values.www.image.pullPolicy }}
          command:
          - 'sh'
          - '-c'
          - >
            echo "Waiting for Pipelines API to come up...";
            until nc -z -w 2 {{ include "pipelines.api.name" . }} {{ .Values.api.service.port }} && echo API ok; do
              sleep 2;
            done;
    {{- if .Values.securityContext.enabled }}
      securityContext:
        runAsUser: {{ .Values.securityContext.uid }}
        fsGroup: {{ .Values.securityContext.gid }}
    {{- end }}
      containers:
        - name: api
          image: "{{ .Values.imageRegistry }}/{{ .Values.www.image.repository }}:{{ default .Chart.AppVersion .Values.www.image.tag }}"
          imagePullPolicy: {{ .Values.www.image.pullPolicy }}
          ports:
            - name: www
              containerPort: 30001
          livenessProbe:
            httpGet:
              path: /
              port: www
            initialDelaySeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: www
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 5
          env:
            - name: SHIPPABLE_API_TOKEN
              valueFrom:
                secretKeyRef: 
                  name: {{ default (include "pipelines.fullname" .) .Values.existingSecret }}
                  key: api-token
          envFrom:
            - configMapRef:
                name: {{ include "pipelines.fullname" . }}-www-config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.www.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.www.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.www.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
