apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pipelines.fullname" . }}-www-config
  labels:
    app.kubernetes.io/name: {{ include "pipelines.name" . }}
    helm.sh/chart: {{ include "pipelines.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  NODE_TLS_REJECT_UNAUTHORIZED: "1" 
  {{- if (and .Values.www.ingress.enabled .Values.www.ingress.tls) }}
  {{- range .Values.www.ingress.hosts }}
  SHIPPABLE_WWW_URL: https://{{ . }}
  {{- end }}
  {{- else if .Values.www.ingress.enabled }}
  {{- range .Values.www.ingress.hosts }}
  SHIPPABLE_WWW_URL: http://{{ . }}
  {{- end }}
  {{- else }}
  SHIPPABLE_WWW_URL: {{ .Values.www.externalUrl }}
  {{- end }}
  SHIPPABLE_WWW_PORT: "30001"
  SHIPPABLE_INT_API_URL: "http://{{ include "pipelines.api.name" . }}:{{ .Values.api.service.port }}"
  {{- if (and .Values.api.ingress.enabled .Values.api.ingress.tls) }}
  {{- range .Values.api.ingress.hosts }}
  SHIPPABLE_PUBLIC_API_URL: https://{{ . }}
  {{- end }}
  {{- else if .Values.api.ingress.enabled }}
  {{- range .Values.api.ingress.hosts }}
  SHIPPABLE_PUBLIC_API_URL: http://{{ . }}
  {{- end }}
  {{- else }}
  SHIPPABLE_PUBLIC_API_URL: {{ .Values.api.externalUrl }}
  {{- end }}
